#!/bin/sh

if [ $# = 2 ]; then
  year=$1
  day=$2
elif [ $# = 1 ]; then
  year=$(date +%Y)
  day=$1
else
  year=$(date +%Y)
  day_zero_padded=$(date +%d)
  day=${day_zero_padded##0}
fi

# This relative path assumes that you are one folder under the root
TOKEN="$(cat .session_token)"

curl -s -JLO --cookie session="$TOKEN" \
  "https://adventofcode.com/$year/day/$day/input"
